build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "freeRTOS"
    - PLATFORMIO_PROJECT_DIR: "zephyr"
    - PLATFORMIO_PROJECT_DIR: "testing/libopencm3"
    - PLATFORMIO_PROJECT_DIR: "testing/cubeMX"

install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=C:\Python36\Scripts;%PATH%
  - cmd: pip3 install -U https://github.com/OS-Q/core/archive/master.zip
  - cmd: platformio platform install ststm32

test_script:
  - cmd: platformio run -s -d %PLATFORMIO_PROJECT_DIR%
