name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

env:
  UPLOAD_BUILD: true

jobs:
  build1:
    name: PIO
    strategy:
      fail-fast: false
      matrix:
        project:
          - "freeRTOS"
          - "zephyr"
          - "testing/libopencm3"
          - "testing/cubeMX"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip

      - name: Build
        run: |
          pio run -d ${{ matrix.project }}

  build2:
    name: QIO
    strategy:
      fail-fast: false
      matrix:
        project:
          - "freeRTOS"
          - "zephyr"
          - "testing/libopencm3"
          - "testing/cubeMX"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/releases/latest/download/S03.zip
          qio platform install https://github.com/OS-Q/P21/releases/latest/download/P21.zip

      - name: Build
        run: |
          qio run -d ${{ matrix.project }}
